Food_Delivery_App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path, include
from django.views.generic import TemplateView

from order.views import ThanksPage
from product.models import Product

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('user.urls', namespace='user')),
    path('', TemplateView.as_view(template_name='index.html'), name='main'),
    path('shop/', include('product.urls', namespace='product')),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('shop/', include('cart.urls', namespace='cart')),
    path('shop/cart/', include('order.urls', namespace='order')),
    path('thanks/', ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart.views import ViewCart, AddProduct, ClearCart

app_name = 'cart'

urlpatterns = (
    path('cart/', ViewCart.as_view(), name='cart'),
    path('ajax/cart/add/', AddProduct.as_view(), name='ajax_add'),
    path('ajax/cart/clear/', ClearCart.as_view(), name='ajax_clear'),
)

order/urls.py
from django.urls import path

from order.views import CheckoutView, PayByCard

app_name = 'order'

urlpatterns = (
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/card/<int:pk>/', PayByCard.as_view(), name='card'),
)

cart/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django_extensions.db.fields.json import JSONField

from product.models import Product


class Cart(models.Model):
    user = models.OneToOneField(
        'user.User',
        on_delete=models.CASCADE,
        related_name='cart',
    )

    products = JSONField(
        default={},
        blank=True
    )

    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0, 'Wrong cost')],
        default=0,
    )

    def refresh(self):
        self.cost = 0
        self.products = {}
        self.save()

    def count_products(self):
        count = 0
        for key, value in self.products.items():
            count += value
        return count

    def __str__(self):
        return f'{self.user.username}\'s cart'

cart/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from cart.models import Cart
from product.models import Product


class ViewCart(ListView):
    model = Cart
    template_name = 'cart/cart.html'
    context_object_name = 'cart'

    def get_queryset(self):
        return Cart.objects.get(user__id=self.request.user.id)


class AddProduct(View):

    def post(self, request):
        cart = Cart.objects.get(user__id=self.request.user.id)
        name1 = request.POST.get('name', None)
        prod_price = Product.objects.get(name=name1).price

        if name1 in cart.products:
            cart.products[name1] += 1
            cart.cost += prod_price
        else:
            cart.products.update({name1: 1})
            cart.cost += prod_price
        cart.save()
        count = cart.count_products()
        data = {
            'msg': f'{name1} has been added to you cart!',
            'count': count,
        }
        return JsonResponse(data)


class ClearCart(View):

    def post(self, request):
        id1 = request.POST.get('id', None)
        ca = Cart.objects.get(id=id1)
        ca.products.clear()
        ca.cost = 0
        ca.save()
        data = {
            'msg': 'Cart cleared',
        }
        return JsonResponse(data)

templates/cart/cart.html
{% extends 'base.html' %}
{% load custom_cart_filters %}
{% block content %}
    <div id="msg-empty" class="w-50 position-relative mx-auto text-center border bg-dark text-light rounded"></div>
    <h3 class="text-center" id="cart-empty"></h3>
    <div id="cart-block">
        {% if cart.products.items %}
            <div class="row text-center">
                <div class="col-3 border">Photo</div>
                <div class="col-3 border">Name</div>
                <div class="col-3 border">Price</div>
                <div class="col-3 border">Count</div>
                {% for key, value in cart.products.items %}
                    <div class="col-3 border">
                        <img style="width: 50px; height: 50px" src="{{ key|get_product_photo_url }}"
                             alt="Product photo">
                    </div>
                    <div class="col-3 border pt-2">
                        <p>{{ key }}</p>
                    </div>
                    <div class="col-3 border pt-2">
                        <p>{{ key|get_product_price }}</p>
                    </div>
                    <div class="col-3 border pt-2">
                        <p>{{ value }}</p>
                    </div>
                {% endfor %}

            </div>
            <div class="content-section clearfix">
                <button class="btn btn-sm btn-secondary mt-4" onclick="clear_cart({{ cart.id }})">Clear cart
                </button>
                <a role="button" class="btn btn-sm btn-success mt-4" href="{% url 'order:checkout' %}">Make order</a>
                <span class="float-right badge badge-secondary mt-4">Sum: {{ cart.cost }}</span>
            </div>
        {% else %}
            <h3 class="text-center">Your cart is empty.</h3>
        {% endif %}
    </div>
{% endblock %}
{% block extrajs %}
    <script>
        function clear_cart(id) {
            $.ajax({
                method: 'post',
                url: '{% url "cart:ajax_clear" %}',
                data: {
                    'id': id,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                dataType: 'json',
                {#success: function(data) {#}
                {#    $('#cart').html(data.count);#}
                //$('#msg').html("data insert successfully").fadeIn('slow') //also show a success message
                success: function (data) {
                    $("#cart-block").remove();
                    $('#cart').html(0);
                    $('#cart-empty').html('Your cart is empty');
                    $('#msg-empty').html(data.msg).fadeIn('slow');
                    $('#msg-empty').delay(1500).fadeOut('slow');
                },
            })
        }
    </script>
{% endblock %}