Food_Delivery_App/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path, include
from django.views.generic import TemplateView

from order.views import ThanksPage
from product.models import Product

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('user.urls', namespace='user')),
    path('', TemplateView.as_view(template_name='index.html'), name='main'),
    path('shop/', include('product.urls', namespace='product')),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('shop/', include('cart.urls', namespace='cart')),
    path('shop/cart/', include('order.urls', namespace='order')),
    path('thanks/', ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart.views import ViewCart, AddProduct, ClearCart

app_name = 'cart'

urlpatterns = (
    path('cart/', ViewCart.as_view(), name='cart'),
    path('ajax/cart/add/', AddProduct.as_view(), name='ajax_add'),
    path('ajax/cart/clear/', ClearCart.as_view(), name='ajax_clear'),
)

product/urls.py
from django.urls import path
from .views import ProductMainPageView, ProductAllView, ProductAboutView

app_name = 'product'

urlpatterns = (
    path('main/', ProductMainPageView.as_view(), name='main'),
    path('products/<str:slug>/', ProductAllView.as_view(), name='all'),
    path('products/<int:pk>/about/', ProductAboutView.as_view(), name='about'),
)

user/urls.py
from django.urls import path

from user.views import UserProfileView, ShowOrders
from .views import UserLogoutView, UserLoginView, UserRegisterView, UserProfileEditView


app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/<slug:slug>/', UserProfileView.as_view(), name='profile'),
    path('profile/<slug:slug>/edit/', UserProfileEditView.as_view(), name='edit'),
    path('profile/<slug:slug>/orders/', ShowOrders.as_view(), name='orders'),
]

templates/base.html
{% load static bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {{ form.media.css }}
    <title>Main Page</title>
</head>
<body class="bg-secondary">
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'product:main' %}">Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'user:profile' user.slug %}">Profile</a>
                    {% endif %}
                    {% if user.is_superuser %}
                        <a class="nav-item nav-link" href="/admin">Admin panel</a>
                    {% endif %}
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'user:logout' %}">Logout</a>
                        <a class="nav-item nav-link" href="{% url 'cart:cart' %}">
                            Cart <span id="cart"
                                       class="badge badge-pill badge-light">{{ user.cart.count_products }}</span>
                        </a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'user:login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'user:register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container bg-light pb-4 rounded border">
    <div id="msg" class="w-50 position-relative mx-auto text-center border bg-dark text-light rounded"></div>
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% block extrajs %}
{% endblock %}
<script>
    function addProduct(name) {
        $.ajax({
            method: 'post',
            url: '{% url "cart:ajax_add" %}',
            data: {
                'name': name,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function (data) {
                $('#cart').html(data.count);
                $('#msg').html(data.msg).fadeIn('slow');
                $('#msg').delay(5000).fadeOut('slow');
            }
        })
    }
</script>
{{ form.media.js }}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center mt-4">Welcome to main page!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="border border-secondary mb-4 mt-4 text-center text-white bg-dark rounded">Thank You!</h1>
    <h2 class="border border-secondary mb-4 mt-4 text-center text-white bg-dark rounded">We recommend:</h2>
    <div class="row justify-content-center">
        {% for product in products %}
            <div class="col-sm-12 col-md-2 border mb-4 text-center">
                <img width="100%" src="{{ product.main_photo.url }}" alt="">
                <h3>{{ product.name }}</h3>
                <p>Price: {{ product.price }}</p>
                <p>About: {{ product.short_description }}</p>
                <a class="btn btn-outline-info btn-block" href="{% url 'product:about' product.id %}">More</a>
                <button class="btn btn-outline-success btn-block" onclick="addProduct('{{ product.name }}')">Add to cart</button>
            </div>
        {% endfor %}
        <a class="btn btn-outline-dark btn-block btn-lg" href="{% url 'product:all' 'all' %}" role="button">See all products</a>
    </div>
{% endblock %}